### ISSUE TITLE
Epic - Favorite Locations

### ISSUE THREAD

**Issue by CoopTang** [CoopTang/express_sweater_weather#14]
## Description
As a registered user, when I want to be able to do the following with my favorite location:
* save locations by posting to `/api/v1/favorites`
* delete locations by deleting to `/api/v1/favorites`
* view the current weather of all my favorite locations by getting `/api/v1/favorites`

### Requirements
- [x] (#15) Create favorites table
- [x] (#16) Add user favorites endpoint
- [x] (#17) List user favorites endpoint
- [x] (#18) Remove user favorites endpoint
