### ISSUE TITLE
Epic - Forecasts

### ISSUE THREAD

**Issue by CoopTang** [CoopTang/express_sweater_weather#8]
## Description
As a user, when I visit the `/api/v1/forecast?location=` endpoint, I want to get the current, hourly, and daily weather for that given location with various info

### Requirements
- [x] (#4) Epic - API Services 
- [x] (#9) User API Key
- [x] (#10) Forecast valid response
- [x] (#11) Forecast invalid response
